### ISSUE TITLE
Should raise `ValueError` and be more specific about exceptions in `def lock_instance`

### ISSUE THREAD

**Issue by XiaonuoGantan** [SPSCommerce/redlock-py#14]
This is just a suggestion. The following code in `redlock/__init__.py`:

```
class Redlock(object):
    ......

    def lock_instance(self, server, resource, val, ttl):
        try:
            return server.set(resource, val, nx=True, px=ttl)
        except:
            return False
```

should handle the case where `ttl` is not an `int`. Raising a `ValueError('ttl is not an int')` seems to be a good choice. Additionally, it might be beneficial to change the api so that it raises certain redis exceptions in the `except` clause so that the caller knows that something is wrong (instance is down, etc.), i.e., letting the caller know exactly why a lock cannot be obtained

**Comment by optimuspaul** [comment]
Great idea, feel free to submit a pull request!

**Comment by XiaonuoGantan** [comment]
Submitted https://github.com/SPSCommerce/redlock-py/pull/15 for this issue.
